### PR TITLE
Add request builder

### PR DESCRIPTION
**Pull request by dheid**
Hi @tholu !

As announced, I did some enhancements to the Matomo Java Client library:

* I added a request builder to create Matomo requests more easily
* I renamed everything from Piwik to Matomo
* I replaced the Glassfish JSON library with Jackson to prevent adding an additional JSON library in Spring projects. Also Jackson is better performing
* I replaced the multiple maps in the Matomo request class with a Guava Multimap to reduce the lines of code and add custom tracking parameters more easily
* I added logging with SLF4J, but only on debug level to not flood any logs of consumers
* I replaced plain setters, getters, constructors and stuff with Lombok to have less bulk code

Old class names and methods will still be there. So most users should not be affected by the update. Nevertheless some things changed and I recommend to use major version 2.

Sorry for the large commit and the unreadable diff. There were some many things to do and I didn't have the time to do it incrementially. Builds are running on my machine, but I cannot use Travis. Perhaps it's a good idea to switch to GitHub Actions soon.

I hope you will merge this pull request! I think the enhancements are worth it.

Best wishes

Daniel

### CODE REVIEW

**Comment by tholu** [comment]
@dheid Travis looks good! Give me some time to check the changes, but this looks awesome already. Any [open issues](https://github.com/matomo-org/matomo-java-tracker/issues) that are already solved with this?

**Comment by dheid** [comment]
@tholu I browsed through the issues and found one that could be fixed in this context: https://github.com/matomo-org/matomo-java-tracker/issues/58

Added another commit to the pull request

**Comment by dheid** [comment]
@tholu And another one: https://github.com/matomo-org/matomo-java-tracker/issues/41 :-)

**Comment by dheid** [comment]
Okay, nothing more to fix or add at the moment. Review can start, @tholu

**Comment by dheid** [comment]
@tholu Friendly reminder (Just want to use the builder in one of my projects and waiting for your review)

**Comment by tholu** [comment]
@dheid I'll try to get this reviewed (and ideally released on Maven central) by tomorrow evening!

**Comment by dheid** [comment]
@tholu Thanks so much!!!

**Comment by tholu** [comment]
@dheid Release to Maven Central is on its way and should be there in the next hours. Thank you!

**Pull request merged**
